name: peft
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - arrow=1.3.0
  - arrow-cpp=11.0.0
  - async-timeout=5.0.1
  - attrs=24.3.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - binaryornot=0.4.4
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - certifi=2024.12.14
  - chardet=4.0.0
  - click=8.1.7
  - cookiecutter=2.6.0
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - dill=0.3.6
  - ffmpeg=4.3
  - freetype=2.12.1
  - frozenlist=1.5.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - grpc-cpp=1.48.2
  - icu=73.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.2.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.52.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.14
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numexpr=2.8.4
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - orc=1.7.4
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.0.0
  - pip=24.2
  - propcache=0.2.0
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.9.0
  - python-dateutil=2.9.0post0
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - responses=0.13.3
  - rich=13.9.4
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - text-unidecode=1.3
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unidecode=1.3.8
  - utf8proc=2.6.1
  - wheel=0.44.0
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.2.1
      - annotated-types==0.7.0
      - anyio==4.7.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bidict==0.23.1
      - bleach==6.2.0
      - cachetools==5.5.0
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - dacite==1.8.1
      - datasets==3.2.0
      - debugpy==1.8.11
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diffusers==0.33.1
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - evaluate==0.4.3
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - fire==0.7.0
      - fonttools==4.55.3
      - fqdn==1.5.1
      - fsspec==2024.9.0
      - gcsfs==2024.9.0.post1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.24.0
      - google-auth==2.37.0
      - google-auth-oauthlib==1.2.1
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - h11==0.14.0
      - h5py==3.14.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.5
      - htmlmin==0.1.12
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.10
      - imagehash==4.3.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mizani==0.11.4
      - msgspec==0.19.0
      - multimethod==1.12
      - nbclient==0.10.2
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nnsight==0.4.6
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patsy==1.0.1
      - peft==0.14.0
      - pexpect==4.9.0
      - phik==0.12.4
      - platformdirs==4.3.6
      - plotnine==0.13.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - proto-plus==1.25.0
      - protobuf==5.29.2
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pyparsing==3.2.0
      - pyreft==0.0.8
      - python-engineio==4.12.0
      - python-json-logger==3.2.1
      - python-socketio==5.13.0
      - pyvene==0.1.6
      - pywavelets==1.6.0
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.4.2
      - scikit-learn==1.6.0
      - scipy==1.13.1
      - seaborn==0.12.2
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - simple-websocket==1.1.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - sympy==1.13.1
      - termcolor==2.5.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tokenizers==0.20.3
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.5.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.45.1
      - triton==3.1.0
      - typeguard==4.4.1
      - uri-template==1.3.0
      - urllib3==2.3.0
      - visions==0.7.6
      - wandb==0.19.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - wordcloud==1.9.4
      - wrapt==2.0.0
      - wsproto==1.2.0
      - ydata-profiling==4.12.1
      - zipp==3.21.0
prefix: /gpfs/work5/0/prjs0370/.conda/envs/peft
